package Rompecabezas;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gaby0
 */
public class Rompecabezas extends javax.swing.JFrame {

    /**
     * Creates new form Rompecabezas
     */
    public Rompecabezas() {
        initComponents();
        setSize(410, 410);
        nueve.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen1.jpg"))); // NOI18N
        uno.setMargin(new java.awt.Insets(1, 14, 1, 14));
        uno.setMaximumSize(new java.awt.Dimension(219, 235));
        uno.setMinimumSize(new java.awt.Dimension(219, 235));
        uno.setPreferredSize(new java.awt.Dimension(219, 235));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        getContentPane().add(uno);

        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen2.jpg"))); // NOI18N
        dos.setMargin(new java.awt.Insets(1, 14, 1, 14));
        dos.setMaximumSize(new java.awt.Dimension(219, 235));
        dos.setMinimumSize(new java.awt.Dimension(219, 235));
        dos.setPreferredSize(new java.awt.Dimension(219, 235));
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        getContentPane().add(dos);

        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen3.jpg"))); // NOI18N
        tres.setMargin(new java.awt.Insets(1, 14, 1, 14));
        tres.setMaximumSize(new java.awt.Dimension(219, 235));
        tres.setMinimumSize(new java.awt.Dimension(219, 235));
        tres.setPreferredSize(new java.awt.Dimension(219, 235));
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        getContentPane().add(tres);

        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen4.jpg"))); // NOI18N
        cuatro.setMaximumSize(new java.awt.Dimension(305, 302));
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        getContentPane().add(cuatro);

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen5.jpg"))); // NOI18N
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        getContentPane().add(cinco);

        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen6.jpg"))); // NOI18N
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        getContentPane().add(seis);

        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen7.jpg"))); // NOI18N
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        getContentPane().add(siete);

        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen8.jpg"))); // NOI18N
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        getContentPane().add(ocho);

        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imagen9.jpg"))); // NOI18N
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        getContentPane().add(nueve);

        pack();
    }// </editor-fold>                        

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if(dos.isVisible()==false){
          dos.setText(uno.getText());
          uno.setVisible(false);
          dos.setVisible(true);
        }
        if(cuatro.isVisible()==false){
          cuatro.setText(uno.getText());
          uno.setVisible(false);
          cuatro.setVisible(true);
        }
    }                                   

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        if(tres.isVisible()==false){
          tres.setText(dos.getText());
          dos.setVisible(false);
          tres.setVisible(true);
        }
        if(uno.isVisible()==false){
          uno.setText(dos.getText());
          dos.setVisible(false);
          uno.setVisible(true);
        }
        if(cinco.isVisible()==false){
          cinco.setText(dos.getText());
          dos.setVisible(false);
          cinco.setVisible(true);
        }
    }                                   

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         if(seis.isVisible()==false){
          seis.setText(tres.getText());
          tres.setVisible(false);
          seis.setVisible(true);
        }
        if(dos.isVisible()==false){
          dos.setText(tres.getText());
          tres.setVisible(false);
          dos.setVisible(true);
        }
    }                                    

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
         if(siete.isVisible()==false){
          siete.setText(cuatro.getText());
          cuatro.setVisible(false);
          siete.setVisible(true);
        }
        if(cinco.isVisible()==false){
          cinco.setText(cuatro.getText());
          cuatro.setVisible(false);
          cinco.setVisible(true);
        }
        if(uno.isVisible()==false){
          uno.setText(cuatro.getText());
          cuatro.setVisible(false);
          uno.setVisible(true);
        }
    }                                      

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         if(cuatro.isVisible()==false){
          cuatro.setText(cinco.getText());
          cinco.setVisible(false);
          cuatro.setVisible(true);
        }
        if(seis.isVisible()==false){
          seis.setText(cinco.getText());
          cinco.setVisible(false);
          seis.setVisible(true);
        }
        if(ocho.isVisible()==false){
          ocho.setText(cinco.getText());
          cinco.setVisible(false);
          ocho.setVisible(true);
        }
        if(dos.isVisible()==false){
          dos.setText(cinco.getText());
          cinco.setVisible(false);
          dos.setVisible(true);
        }
    }                                     

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
         if(nueve.isVisible()==false){
          nueve.setText(seis.getText());
          seis.setVisible(false);
          nueve.setVisible(true);
        }
        if(cinco.isVisible()==false){
          cinco.setText(seis.getText());
          seis.setVisible(false);
          cinco.setVisible(true);
        }
        if(tres.isVisible()==false){
          tres.setText(seis.getText());
          seis.setVisible(false);
          tres.setVisible(true);
        }
    }                                    

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         if(ocho.isVisible()==false){
          ocho.setText(siete.getText());
          siete.setVisible(false);
          ocho.setVisible(true);
        }
        if(cuatro.isVisible()==false){
          cuatro.setText(siete.getText());
          siete.setVisible(false);
          cuatro.setVisible(true);
        }
    }                                     

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
          if(nueve.isVisible()==false){
          nueve.setText(ocho.getText());
          ocho.setVisible(false);
          nueve.setVisible(true);
        }
        if(siete.isVisible()==false){
          siete.setText(ocho.getText());
          ocho.setVisible(false);
          siete.setVisible(true);
        }
        if(cinco.isVisible()==false){
          cinco.setText(ocho.getText());
          ocho.setVisible(false);
          cinco.setVisible(true);
        }
    }                                    

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if(seis.isVisible()==false){
          seis.setText(nueve.getText());
          nueve.setVisible(false);
          seis.setVisible(true);
        }
        if(ocho.isVisible()==false){
          ocho.setText(nueve.getText());
          nueve.setVisible(false);
          ocho.setVisible(true);
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rompecabezas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Rompecabezas().setVisible(true);
            }
            
            private void setImageLabel(JLabel labelName, String root, Icon icon){
                ImageIcon image = new ImageIcon(root);
                labelName.setIcon(icon);
                this.repaint();
            }

            private void repaint() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration                   
}